### PR TITLE
Add support to adjust column width

### PR DESCRIPTION
**Pull request by simonqbs**
Hi!
I needed a way to adjust column width. What do you think about this solution?

### CODE REVIEW

**Comment by rigofunc** [comment]
The default behavior had called sheet.AutoSizeColumn(i); so I think not to do all things in one solution.

**Comment by simonqbs** [comment]
Ok, how do you suggest doing it?

**Comment by rigofunc** [comment]
Not to support this requirement.

**Comment by simonqbs** [comment]
But wouldn't it be nice to have an option to be able to adjust column width? Maybe not this solution but in some other way? My use case is that when using filters some of the column text get's hidden, but by adjusting column width I can work around that. But I understand if you don't want to support this feature :-)

edit: added use case

**Comment by rigofunc** [comment]
Yes, I want not to support this feature, because I think the end user can operate the Excel. Or you can tell me why your end user doesn't to adjust column width by manual?

**Comment by simonqbs** [comment]
I have  some use cases where some columns needs to be wider than others, depending on the content within.

**Comment by rigofunc** [comment]
> depending on the content within.

sheet.AutoSizeColumn(i); do that thing.

**Comment by rigofunc** [comment]
Anyone has the same requirement? Or this requirement is reasonable?

**Pull request closed without merging**
